FROM ubuntu:20.04

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10 

WORKDIR /vehicleapi
COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

RUN apt-get update 
RUN apt-get upgrade -y
