# /********************************************************************************
# * Copyright (c) 2021 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# ********************************************************************************/


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicleapi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicleapi.proto',
  package='vehicleapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10vehicleapi.proto\x12\nvehicleapi\"&\n\x12SetPositionRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\"\x15\n\x13SetPositionResponse2b\n\x0eSeatController\x12P\n\x0bSetPosition\x12\x1e.vehicleapi.SetPositionRequest\x1a\x1f.vehicleapi.SetPositionResponse\"\x00\x62\x06proto3'
)


_SETPOSITIONREQUEST = _descriptor.Descriptor(
  name='SetPositionRequest',
  full_name='vehicleapi.SetPositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='vehicleapi.SetPositionRequest.position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)


_SETPOSITIONRESPONSE = _descriptor.Descriptor(
  name='SetPositionResponse',
  full_name='vehicleapi.SetPositionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['SetPositionRequest'] = _SETPOSITIONREQUEST
DESCRIPTOR.message_types_by_name['SetPositionResponse'] = _SETPOSITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetPositionRequest = _reflection.GeneratedProtocolMessageType('SetPositionRequest', (_message.Message,), {
  'DESCRIPTOR': _SETPOSITIONREQUEST,
  '__module__': 'vehicleapi_pb2'
  # @@protoc_insertion_point(class_scope:vehicleapi.SetPositionRequest)
  })
_sym_db.RegisterMessage(SetPositionRequest)


SetPositionResponse = _reflection.GeneratedProtocolMessageType('SetPositionResponse', (_message.Message,), {
  'DESCRIPTOR': _SETPOSITIONRESPONSE,
  '__module__': 'vehicleapi_pb2'
  # @@protoc_insertion_point(class_scope:vehicleapi.SetPositionResponse)
  })
_sym_db.RegisterMessage(SetPositionResponse)


_SEATCONTROLLER = _descriptor.ServiceDescriptor(
  name='SeatController',
  full_name='vehicleapi.SeatController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=193,
  methods=[
          _descriptor.MethodDescriptor(
                                      name='SetPosition',
                                      full_name='vehicleapi.SeatController.SetPosition',
                                      index=0,
                                      containing_service=None,
                                      input_type=_SETPOSITIONREQUEST,
                                      output_type=_SETPOSITIONRESPONSE,
                                      serialized_options=None,
                                      create_key=_descriptor._internal_create_key,
                                      ),
          ])
_sym_db.RegisterServiceDescriptor(_SEATCONTROLLER)

DESCRIPTOR.services_by_name['SeatController'] = _SEATCONTROLLER

# @@protoc_insertion_point(module_scope)
