"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SeatComponent(_SeatComponent, metaclass=_SeatComponentEnumTypeWrapper):
    """*
    @brief
    """

    pass

class _SeatComponent:
    V = typing.NewType("V", builtins.int)

class _SeatComponentEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SeatComponent.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BASE = SeatComponent.V(0)
    CUSHION = SeatComponent.V(1)
    LUMBAR = SeatComponent.V(2)
    SIDE_BOLSTER = SeatComponent.V(3)
    HEAD_RESTRAINT = SeatComponent.V(4)

BASE = SeatComponent.V(0)
CUSHION = SeatComponent.V(1)
LUMBAR = SeatComponent.V(2)
SIDE_BOLSTER = SeatComponent.V(3)
HEAD_RESTRAINT = SeatComponent.V(4)
global___SeatComponent = SeatComponent

class MoveRequest(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEAT_FIELD_NUMBER: builtins.int
    @property
    def seat(self) -> global___Seat:
        """The desired seat position"""
        pass
    def __init__(
        self,
        *,
        seat: typing.Optional[global___Seat] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["seat", b"seat"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["seat", b"seat"]
    ) -> None: ...

global___MoveRequest = MoveRequest

class MoveReply(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___MoveReply = MoveReply

class MoveComponentRequest(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEAT_FIELD_NUMBER: builtins.int
    COMPONENT_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    @property
    def seat(self) -> global___SeatLocation:
        """The seat location to change"""
        pass
    component: global___SeatComponent.V = ...
    """The component position to change"""

    position: builtins.int = ...
    """The desired position to move the component to"""
    def __init__(
        self,
        *,
        seat: typing.Optional[global___SeatLocation] = ...,
        component: global___SeatComponent.V = ...,
        position: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["seat", b"seat"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "component", b"component", "position", b"position", "seat", b"seat"
        ],
    ) -> None: ...

global___MoveComponentRequest = MoveComponentRequest

class MoveComponentReply(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___MoveComponentReply = MoveComponentReply

class CurrentPositionRequest(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ROW_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    row: builtins.int = ...
    """The desired seat to row query"""

    index: builtins.int = ...
    """The desired seat index to query"""
    def __init__(
        self,
        *,
        row: builtins.int = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["index", b"index", "row", b"row"]
    ) -> None: ...

global___CurrentPositionRequest = CurrentPositionRequest

class CurrentPositionReply(google.protobuf.message.Message):
    """*
    @brief
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEAT_FIELD_NUMBER: builtins.int
    @property
    def seat(self) -> global___Seat:
        """The seat state that was requested"""
        pass
    def __init__(
        self,
        *,
        seat: typing.Optional[global___Seat] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["seat", b"seat"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["seat", b"seat"]
    ) -> None: ...

global___CurrentPositionReply = CurrentPositionReply

class Seat(google.protobuf.message.Message):
    """*
    @brief The structure used to describe the seat's position in the vehicle
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCATION_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    @property
    def location(self) -> global___SeatLocation:
        """The location of the seat in the vehicle"""
        pass
    @property
    def position(self) -> global___Position:
        """The various positions of the seat"""
        pass
    def __init__(
        self,
        *,
        location: typing.Optional[global___SeatLocation] = ...,
        position: typing.Optional[global___Position] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "location", b"location", "position", b"position"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "location", b"location", "position", b"position"
        ],
    ) -> None: ...

global___Seat = Seat

class SeatLocation(google.protobuf.message.Message):
    """*
    @brief The location of the seat in the vehicle
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ROW_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    row: builtins.int = ...
    """The row, front 0 and +1 toward rear"""

    index: builtins.int = ...
    """The index within the row, 0 left most, +1 toward right"""
    def __init__(
        self,
        *,
        row: builtins.int = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["index", b"index", "row", b"row"]
    ) -> None: ...

global___SeatLocation = SeatLocation

class Position(google.protobuf.message.Message):
    """*
    @brief The position of the entire seat
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BASE_FIELD_NUMBER: builtins.int
    CUSHION_FIELD_NUMBER: builtins.int
    LUMBAR_FIELD_NUMBER: builtins.int
    SIDE_BOLSTER_FIELD_NUMBER: builtins.int
    HEAD_RESTRAINT_FIELD_NUMBER: builtins.int
    base: builtins.int = ...
    """The position of the base 0 front, 1000 back"""

    cushion: builtins.int = ...
    """The position of the cushion 0 short, 1000 long"""

    lumbar: builtins.int = ...
    """The position of the lumbar support"""

    side_bolster: builtins.int = ...
    """The position of the side bolster"""

    head_restraint: builtins.int = ...
    """The position of the head restraint 0 down, 1000 up"""
    def __init__(
        self,
        *,
        base: builtins.int = ...,
        cushion: builtins.int = ...,
        lumbar: builtins.int = ...,
        side_bolster: builtins.int = ...,
        head_restraint: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "base",
            b"base",
            "cushion",
            b"cushion",
            "head_restraint",
            b"head_restraint",
            "lumbar",
            b"lumbar",
            "side_bolster",
            b"side_bolster",
        ],
    ) -> None: ...

global___Position = Position
