FROM python:3.9-slim-bullseye

RUN apt-get update 
RUN apt-get upgrade -y

WORKDIR /vehicleapi
ADD ./* $HOME/vehicleapi/
RUN pip3 install -r requirements.txt

LABEL org.opencontainers.image.source="https://github.com/softwaredefinedvehicle/vehicle-app-python-template"

