# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swdc_comfort_seats.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='swdc_comfort_seats.proto',
  package='swdc.comfort',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18swdc_comfort_seats.proto\x12\x0cswdc.comfort\"/\n\x0bMoveRequest\x12 \n\x04seat\x18\x01 \x01(\x0b\x32\x12.swdc.comfort.Seat\"\x0b\n\tMoveReply\"\x82\x01\n\x14MoveComponentRequest\x12(\n\x04seat\x18\x01 \x01(\x0b\x32\x1a.swdc.comfort.SeatLocation\x12.\n\tcomponent\x18\x02 \x01(\x0e\x32\x1b.swdc.comfort.SeatComponent\x12\x10\n\x08position\x18\x03 \x01(\x05\"\x14\n\x12MoveComponentReply\"4\n\x16\x43urrentPositionRequest\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\"8\n\x14\x43urrentPositionReply\x12 \n\x04seat\x18\x01 \x01(\x0b\x32\x12.swdc.comfort.Seat\"^\n\x04Seat\x12,\n\x08location\x18\x01 \x01(\x0b\x32\x1a.swdc.comfort.SeatLocation\x12(\n\x08position\x18\x02 \x01(\x0b\x32\x16.swdc.comfort.Position\"*\n\x0cSeatLocation\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\"g\n\x08Position\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ushion\x18\x02 \x01(\x05\x12\x0e\n\x06lumbar\x18\x03 \x01(\x05\x12\x14\n\x0cside_bolster\x18\x04 \x01(\x05\x12\x16\n\x0ehead_restraint\x18\x05 \x01(\x05*X\n\rSeatComponent\x12\x08\n\x04\x42\x41SE\x10\x00\x12\x0b\n\x07\x43USHION\x10\x01\x12\n\n\x06LUMBAR\x10\x02\x12\x10\n\x0cSIDE_BOLSTER\x10\x03\x12\x12\n\x0eHEAD_RESTRAINT\x10\x04\x32\xf7\x01\n\x05Seats\x12:\n\x04Move\x12\x19.swdc.comfort.MoveRequest\x1a\x17.swdc.comfort.MoveReply\x12U\n\rMoveComponent\x12\".swdc.comfort.MoveComponentRequest\x1a .swdc.comfort.MoveComponentReply\x12[\n\x0f\x43urrentPosition\x12$.swdc.comfort.CurrentPositionRequest\x1a\".swdc.comfort.CurrentPositionReplyb\x06proto3'
)

_SEATCOMPONENT = _descriptor.EnumDescriptor(
  name='SeatComponent',
  full_name='swdc.comfort.SeatComponent',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CUSHION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LUMBAR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIDE_BOLSTER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HEAD_RESTRAINT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=616,
  serialized_end=704,
)
_sym_db.RegisterEnumDescriptor(_SEATCOMPONENT)

SeatComponent = enum_type_wrapper.EnumTypeWrapper(_SEATCOMPONENT)
BASE = 0
CUSHION = 1
LUMBAR = 2
SIDE_BOLSTER = 3
HEAD_RESTRAINT = 4



_MOVEREQUEST = _descriptor.Descriptor(
  name='MoveRequest',
  full_name='swdc.comfort.MoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seat', full_name='swdc.comfort.MoveRequest.seat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=89,
)


_MOVEREPLY = _descriptor.Descriptor(
  name='MoveReply',
  full_name='swdc.comfort.MoveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=102,
)


_MOVECOMPONENTREQUEST = _descriptor.Descriptor(
  name='MoveComponentRequest',
  full_name='swdc.comfort.MoveComponentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seat', full_name='swdc.comfort.MoveComponentRequest.seat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='component', full_name='swdc.comfort.MoveComponentRequest.component', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='swdc.comfort.MoveComponentRequest.position', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=235,
)


_MOVECOMPONENTREPLY = _descriptor.Descriptor(
  name='MoveComponentReply',
  full_name='swdc.comfort.MoveComponentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=257,
)


_CURRENTPOSITIONREQUEST = _descriptor.Descriptor(
  name='CurrentPositionRequest',
  full_name='swdc.comfort.CurrentPositionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='swdc.comfort.CurrentPositionRequest.row', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='swdc.comfort.CurrentPositionRequest.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=311,
)


_CURRENTPOSITIONREPLY = _descriptor.Descriptor(
  name='CurrentPositionReply',
  full_name='swdc.comfort.CurrentPositionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seat', full_name='swdc.comfort.CurrentPositionReply.seat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=369,
)


_SEAT = _descriptor.Descriptor(
  name='Seat',
  full_name='swdc.comfort.Seat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='swdc.comfort.Seat.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='swdc.comfort.Seat.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=465,
)


_SEATLOCATION = _descriptor.Descriptor(
  name='SeatLocation',
  full_name='swdc.comfort.SeatLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='swdc.comfort.SeatLocation.row', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='swdc.comfort.SeatLocation.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=509,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='swdc.comfort.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='swdc.comfort.Position.base', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cushion', full_name='swdc.comfort.Position.cushion', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lumbar', full_name='swdc.comfort.Position.lumbar', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side_bolster', full_name='swdc.comfort.Position.side_bolster', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_restraint', full_name='swdc.comfort.Position.head_restraint', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=614,
)

_MOVEREQUEST.fields_by_name['seat'].message_type = _SEAT
_MOVECOMPONENTREQUEST.fields_by_name['seat'].message_type = _SEATLOCATION
_MOVECOMPONENTREQUEST.fields_by_name['component'].enum_type = _SEATCOMPONENT
_CURRENTPOSITIONREPLY.fields_by_name['seat'].message_type = _SEAT
_SEAT.fields_by_name['location'].message_type = _SEATLOCATION
_SEAT.fields_by_name['position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['MoveRequest'] = _MOVEREQUEST
DESCRIPTOR.message_types_by_name['MoveReply'] = _MOVEREPLY
DESCRIPTOR.message_types_by_name['MoveComponentRequest'] = _MOVECOMPONENTREQUEST
DESCRIPTOR.message_types_by_name['MoveComponentReply'] = _MOVECOMPONENTREPLY
DESCRIPTOR.message_types_by_name['CurrentPositionRequest'] = _CURRENTPOSITIONREQUEST
DESCRIPTOR.message_types_by_name['CurrentPositionReply'] = _CURRENTPOSITIONREPLY
DESCRIPTOR.message_types_by_name['Seat'] = _SEAT
DESCRIPTOR.message_types_by_name['SeatLocation'] = _SEATLOCATION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.enum_types_by_name['SeatComponent'] = _SEATCOMPONENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoveRequest = _reflection.GeneratedProtocolMessageType('MoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.MoveRequest)
  })
_sym_db.RegisterMessage(MoveRequest)

MoveReply = _reflection.GeneratedProtocolMessageType('MoveReply', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREPLY,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.MoveReply)
  })
_sym_db.RegisterMessage(MoveReply)

MoveComponentRequest = _reflection.GeneratedProtocolMessageType('MoveComponentRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVECOMPONENTREQUEST,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.MoveComponentRequest)
  })
_sym_db.RegisterMessage(MoveComponentRequest)

MoveComponentReply = _reflection.GeneratedProtocolMessageType('MoveComponentReply', (_message.Message,), {
  'DESCRIPTOR' : _MOVECOMPONENTREPLY,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.MoveComponentReply)
  })
_sym_db.RegisterMessage(MoveComponentReply)

CurrentPositionRequest = _reflection.GeneratedProtocolMessageType('CurrentPositionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTPOSITIONREQUEST,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.CurrentPositionRequest)
  })
_sym_db.RegisterMessage(CurrentPositionRequest)

CurrentPositionReply = _reflection.GeneratedProtocolMessageType('CurrentPositionReply', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTPOSITIONREPLY,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.CurrentPositionReply)
  })
_sym_db.RegisterMessage(CurrentPositionReply)

Seat = _reflection.GeneratedProtocolMessageType('Seat', (_message.Message,), {
  'DESCRIPTOR' : _SEAT,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.Seat)
  })
_sym_db.RegisterMessage(Seat)

SeatLocation = _reflection.GeneratedProtocolMessageType('SeatLocation', (_message.Message,), {
  'DESCRIPTOR' : _SEATLOCATION,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.SeatLocation)
  })
_sym_db.RegisterMessage(SeatLocation)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'swdc_comfort_seats_pb2'
  # @@protoc_insertion_point(class_scope:swdc.comfort.Position)
  })
_sym_db.RegisterMessage(Position)



_SEATS = _descriptor.ServiceDescriptor(
  name='Seats',
  full_name='swdc.comfort.Seats',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=707,
  serialized_end=954,
  methods=[
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='swdc.comfort.Seats.Move',
    index=0,
    containing_service=None,
    input_type=_MOVEREQUEST,
    output_type=_MOVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MoveComponent',
    full_name='swdc.comfort.Seats.MoveComponent',
    index=1,
    containing_service=None,
    input_type=_MOVECOMPONENTREQUEST,
    output_type=_MOVECOMPONENTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CurrentPosition',
    full_name='swdc.comfort.Seats.CurrentPosition',
    index=2,
    containing_service=None,
    input_type=_CURRENTPOSITIONREQUEST,
    output_type=_CURRENTPOSITIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEATS)

DESCRIPTOR.services_by_name['Seats'] = _SEATS

# @@protoc_insertion_point(module_scope)
